### ISSUE TITLE
resin os install crashes

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/resin-cli#12]
Throws this:
```
pablo@pablo-laptop:~/resin/resin-starter-kit-python$ sudo resin os install ../starterpython.img /dev/mmcblk0
? This will completely erase /dev/mmcblk0. Are you sure you want to continue? Yes

/usr/lib/node_modules/resin-cli/node_modules/resin-cli-visuals/build/widgets/progress.js:51
    this.eraseLastLine();
         ^
TypeError: Object #<Through2> has no method 'eraseLastLine'
    at Through2.module.exports.Progress.update (/usr/lib/node_modules/resin-cli/node_modules/resin-cli-visuals/build/widgets/progress.js:51:10)
    at Through2.emit (events.js:95:17)
    at emit (/usr/lib/node_modules/resin-cli/node_modules/progress-stream/index.js:36:6)
    at Through2.write [as _transform] (/usr/lib/node_modules/resin-cli/node_modules/progress-stream/index.js:45:33)
    at Through2.Transform._read (_stream_transform.js:179:10)
    at Through2.Readable.read (_stream_readable.js:340:10)
    at flow (_stream_readable.js:607:52)
    at WriteStream.<anonymous> (_stream_readable.js:591:7)
    at WriteStream.emit (events.js:92:17)
    at onwriteDrain (_stream_writable.js:288:12)
    at afterWrite (_stream_writable.js:276:5)
    at onwrite (_stream_writable.js:269:7)
    at WritableState.onwrite (_stream_writable.js:96:5)
    at fs.js:1694:5
    at Object.wrapper [as oncomplete] (fs.js:521:5)
```

**Comment by jviotti** [comment]
Fixed in https://github.com/resin-io/resin-cli/commit/caa4fcf75471b0cd965e6fcf50868378f5312936.
