### ISSUE TITLE
Error after selecting network config. (v 2.2.0)

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io/resin-cli#267]
After I select wifi or ethernet, it throws this:

```
Unhandled rejection SyntaxError: Invalid MBR boot signature. Expected 0xAA55, but saw 0xC9B9
    at Function.MBR.detectFormat (/usr/local/lib/node_modules/resin-cli/node_modules/resin-device-init/node_modules/resin-image-fs/node_modules/mbr/lib/mbr.js:83:11)
    at Function.MBR.parse (/usr/local/lib/node_modules/resin-cli/node_modules/resin-device-init/node_modules/resin-image-fs/node_modules/mbr/lib/mbr.js:64:20)
    at new MBR (/usr/local/lib/node_modules/resin-cli/node_modules/resin-device-init/node_modules/resin-image-fs/node_modules/mbr/lib/mbr.js:14:16)
    at exports.parse (/usr/local/lib/node_modules/resin-cli/node_modules/resin-device-init/node_modules/resin-image-fs/node_modules/partitioninfo/build/boot-record.js:58:10)
    at tryCatcher (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by jviotti** [comment]
@craig-mulligan What was the command that triggered the error?

It happens when the CLI tries to read the MBR of an image to analyse it's partitions before configuring, but for some reason the MBR is invalid. I would suggest checking that:

- The image you're trying to modify is indeed a valid image containing a MBR (maybe it's corrupted?).
- If the error happened when trying to read the `config.json` from a provisioned device, can you make sure you selected the correct drive (maybe you selected an un-provisioned drive instead)?

Anyway, I think we can hugely improve this error message.

**Comment by craig-mulligan** [comment]
@jviotti encountered when running `resin quickstart`. It downloaded a fresh copy of the OS so it's possible that was corrupted somehow. Also just realized I didn't run the command with sudo, although this error seems unrelated.

**Comment by craig-mulligan** [comment]
@jviotti where are the images stored? So I can delete and try again

**Comment by jviotti** [comment]
@craig-mulligan `resin quickstart` now automatically prompts you to run with `sudo` only when needed, to prevent other files being owned by root by accident (which was the source of other issues).

The images are stored in `$HOME/.resin/cache`.

**Comment by craig-mulligan** [comment]
@jviotti I deleted the image and re-downloaded a new image, still running into the same issue. :/

**Comment by jviotti** [comment]
@craig-mulligan Can you paste the whole output, since you run the command?

**Comment by craig-mulligan** [comment]
```
➜  ~  sudo resin quickstart
Password:
? Select an application myApp
Getting device operating system for raspberry-pi2
The image was downloaded to /tmp/tmp-7475SuG9WYIsjorA
Registering to myApp: 029ac06b54752e37237d8647ff826d6b04c3fc97a75a615022f1c950e8a25d
Configuring operating system image
? Network Connection ethernet
Unhandled rejection SyntaxError: Invalid MBR boot signature. Expected 0xAA55, but saw 0xC9B9
    at Function.MBR.detectFormat (/usr/local/lib/node_modules/resin-cli/node_modules/resin-device-init/node_modules/resin-image-fs/node_modules/mbr/lib/mbr.js:83:11)
    at Function.MBR.parse (/usr/local/lib/node_modules/resin-cli/node_modules/resin-device-init/node_modules/resin-image-fs/node_modules/mbr/lib/mbr.js:64:20)
    at new MBR (/usr/local/lib/node_modules/resin-cli/node_modules/resin-device-init/node_modules/resin-image-fs/node_modules/mbr/lib/mbr.js:14:16)
    at exports.parse (/usr/local/lib/node_modules/resin-cli/node_modules/resin-device-init/node_modules/resin-image-fs/node_modules/partitioninfo/build/boot-record.js:58:10)
    at tryCatcher (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/resin-cli/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
➜  ~  
```

**Comment by jviotti** [comment]
@craig-mulligan I've tried many ways to reproduce this without luck. Can you upload the raspberry pi 2 image the CLI is using (located in `$HOME/.resin/cache/raspberry-pi2.img`) somewhere so I can inspect in detail?

**Comment by jviotti** [comment]
I think I know the cause of the issue:

There were recent changes in `resin-request` to read the brand new `x-transfer-length` HTTP header which contains the compressed transfer length for static images.

The change introduced a subtle bug that makes `resin-request` pipe compressed data using uncompressed content length information.

I'll publish a PR soon.
