### ISSUE TITLE
preload fails with "builds is not defined"

### ISSUE THREAD

**Issue by BrianAdams** [resin-io/resin-cli#629]
The script crashes right after successfully building the resin-preload docker image.  Problem resolving the builds? 

>resin preload $(pwd)/resin.img --dockerHost docker --dockerPort 2375 --api-key $RESIN_PROD_APIKEY --app $appid --commit ${lastcommit}
```
Step 1/7 : FROM docker:17.06.1-ce-dind
 ---> 9e3d126eb84f
Step 2/7 : RUN apk update && apk add --no-cache python3 parted btrfs-progs docker util-linux inotify-tools sfdisk
 ---> Running in 6e3f11a93e47
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
v3.6.2-80-gd6beefe139 [http://dl-cdn.alpinelinux.org/alpine/v3.6/main]
v3.6.2-78-gc30bfa742f [http://dl-cdn.alpinelinux.org/alpine/v3.6/community]
OK: 8439 distinct packages available
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
(1/21) Installing device-mapper-libs (2.02.168-r3)
(2/21) Installing libseccomp (2.3.2-r0)
(3/21) Installing docker (17.05.0-r0)
Executing docker-17.05.0-r0.pre-install
(4/21) Installing inotify-tools (3.14-r2)
(5/21) Installing ncurses-terminfo-base (6.0-r8)
(6/21) Installing ncurses-terminfo (6.0-r8)
(7/21) Installing ncurses-libs (6.0-r8)
(8/21) Installing readline (6.3.008-r5)
(9/21) Installing parted (3.2-r5)
(10/21) Installing libbz2 (1.0.6-r5)
(11/21) Installing expat (2.2.0-r1)
(12/21) Installing libffi (3.2.1-r3)
(13/21) Installing gdbm (1.12-r0)
(14/21) Installing sqlite-libs (3.18.0-r0)
(15/21) Installing python3 (3.6.1-r2)
(16/21) Installing libfdisk (2.28.2-r2)
(17/21) Installing libsmartcols (2.28.2-r2)
(18/21) Installing sfdisk (2.28.2-r2)
(19/21) Installing libmount (2.28.2-r2)
(20/21) Installing findmnt (2.28.2-r2)
(21/21) Installing util-linux (2.28.2-r2)
Executing busybox-1.26.2-r5.trigger
OK: 172 MiB in 47 packages
 ---> cf0807a5b161
Removing intermediate container 6e3f11a93e47
Step 3/7 : COPY ./requirements.txt /tmp/
 ---> 10e1f1b17b53
Removing intermediate container fc86cc39620f
Step 4/7 : RUN pip3 install -r /tmp/requirements.txt
 ---> Running in 8325dc4b37d2
Collecting sh==1.12.14 (from -r /tmp/requirements.txt (line 1))
  Downloading sh-1.12.14-py2.py3-none-any.whl
Installing collected packages: sh
Successfully installed sh-1.12.14
 ---> 196a0b2e1d91
Removing intermediate container 8325dc4b37d2
Step 5/7 : COPY ./src /usr/src/app
 ---> 0117605c810d
Removing intermediate container 643c7f9067a2
Step 6/7 : WORKDIR /usr/src/app
 ---> 515324e85cc4
Removing intermediate container 518ed4a62c84
Step 7/7 : CMD /usr/src/app/preload.py
 ---> Running in fb26da6385c3
 ---> 003e73ca07ab
Removing intermediate container fb26da6385c3
Successfully built 003e73ca07ab
Successfully tagged resin/resin-preload:latest
ReferenceError: builds is not defined
    at /usr/lib/node_modules/resin-cli/build/actions/preload.js:191:25
    at tryCatcher (/usr/lib/node_modules/resin-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/usr/lib/node_modules/resin-cli/node_modules/bluebird/js/release/method.js:39:29)
    at /usr/lib/node_modules/resin-cli/build/actions/preload.js:189:32
    at tryCatcher (/usr/lib/node_modules/resin-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/resin-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/resin-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/resin-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/resin-cli/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/lib/node_modules/resin-cli/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/resin-cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/resin-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by BrianAdams** [comment]
I suspect I have the wrong appid, and that the error check is failing because builds is null vs empty.

**Comment by BrianAdams** [comment]
Cleaned up my command line call. That was not the issue, still getting the builds is not defined error when there are 8 or so builds in that applicaiton.

**Comment by BrianAdams** [comment]
I've looked at the code, it's not clear where the builds variable is defined. Should it be Application.builds?

**Comment by zvin** [comment]
Hi @BrianAdams , this is now fixed in the master branch, thanks for reporting it.
