### ISSUE TITLE
Help command: TypeError: _.object is not a function

### ISSUE THREAD

**Issue by BrianAdams** [resin-io/resin-cli#636]
When bringing up the command line help using today's master repo version (2ad789457f0a4c187912147519f0c9f04fa73522) of resin-cli, there is an error when it attempts to enumerate the possible options:

> resin help preload
```
Usage: preload <image>

Warning: "resin preload" requires Docker to be correctly installed in
your shell environment. For more information (including Windows support)
please check the README here: https://github.com/resin-io/resin-cli .

Use this command to preload an application to a local disk image with a
built commit from Resin.io.
This can be used with cloud builds, or images deployed with resin deploy.

Examples:
  $ resin preload resin.img --app 1234 --commit e1f2592fc6ee949e68756d4f4a48e49bff8d72a0 --splash-image some-image.png
  $ resin preload resin.img

Options:

TypeError: _.object is not a function
    at parse (/usr/local/lib/node_modules/resin-cli/build/actions/help.js:31:12)
    at /usr/local/lib/node_modules/resin-cli/build/actions/help.js:107:13
    at /usr/local/lib/node_modules/resin-cli/node_modules/capitano/build/state.js:31:14
    at /usr/local/lib/node_modules/resin-cli/node_modules/capitano/build/signature.js:106:16
    at /usr/local/lib/node_modules/resin-cli/node_modules/capitano/build/signature.js:148:20
    at /usr/local/lib/node_modules/resin-cli/node_modules/async/lib/async.js:181:20
    at Immediate.iterate [as _onImmediate] (/usr/local/lib/node_modules/resin-cli/node_modules/async/lib/async.js:262:13)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by zvin** [comment]
lodash v4.0.0 removed `_.object`

see  https://github.com/lodash/lodash/wiki/Changelog
> Removed _.object in favor of _.fromPairs or _.zipObject
