### ISSUE TITLE
Convert Docker.template file for use with local

### ISSUE THREAD

**Issue by aj-ptw** [resin-io/resin-cli#740]
- **resin-cli version:** 6.10.2
- Raspberry pi debian stretch 

Issue #504 seems relevant but ultimately not helpful enough to resolve.

I duplicated and renamed `Dockerfile.template` to `Dockerfile` and then tried:

```bash
$ sudo resin local push 963d724.local -s .
* Building..
- Stopping and removing any previous 'local-app' container
Step 1/16 : FROM resin/%%RESIN_MACHINE_NAME%%-debian:stretch
rdt push failed. Error: invalid reference format: repository name must be lowercase Error: invalid reference format: repository name must be lowercase
    at Stream.<anonymous> (/Users/aj/.npm-packages/lib/node_modules/resin-cli/node_modules/resin-sync/build/docker-utils.js:146:23)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:188:7)
    at drain (/Users/aj/.npm-packages/lib/node_modules/resin-cli/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/Users/aj/.npm-packages/lib/node_modules/resin-cli/node_modules/through/index.js:45:5)
    at Parser.parser.onToken (/Users/aj/.npm-packages/lib/node_modules/resin-cli/node_modules/resin-sync/node_modules/JSONStream/index.js:132:18)
    at Parser.proto.write (/Users/aj/.npm-packages/lib/node_modules/resin-cli/node_modules/resin-sync/node_modules/jsonparse/jsonparse.js:135:34)
    at Stream.<anonymous> (/Users/aj/.npm-packages/lib/node_modules/resin-cli/node_modules/resin-sync/node_modules/JSONStream/index.js:23:12)
    at Stream.stream.write (/Users/aj/.npm-packages/lib/node_modules/resin-cli/node_modules/through/index.js:26:11)
    at IncomingMessage.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at IncomingMessage.Readable.push (_stream_readable.js:134:10)
    at HTTPParser.parserOnBody (_http_common.js:123:22)
    at Socket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
```

and then

```
$ sudo resin local push 963d724.local -s .
* Building..
- Stopping and removing any previous 'local-app' container
Step 1/16 : FROM resin/raspberrypi-debian:stretch
rdt push failed. Error: manifest for resin/raspberrypi-debian:stretch not found Error: manifest for resin/raspberrypi-debian:stretch not found
    at Stream.<anonymous> (/Users/aj/.npm-packages/lib/node_modules/resin-cli/node_modules/resin-sync/build/docker-utils.js:146:23)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:188:7)
    at drain (/Users/aj/.npm-packages/lib/node_modules/resin-cli/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/Users/aj/.npm-packages/lib/node_modules/resin-cli/node_modules/through/index.js:45:5)
    at Parser.parser.onToken (/Users/aj/.npm-packages/lib/node_modules/resin-cli/node_modules/resin-sync/node_modules/JSONStream/index.js:132:18)
    at Parser.proto.write (/Users/aj/.npm-packages/lib/node_modules/resin-cli/node_modules/resin-sync/node_modules/jsonparse/jsonparse.js:135:34)
    at Stream.<anonymous> (/Users/aj/.npm-packages/lib/node_modules/resin-cli/node_modules/resin-sync/node_modules/JSONStream/index.js:23:12)
    at Stream.stream.write (/Users/aj/.npm-packages/lib/node_modules/resin-cli/node_modules/through/index.js:26:11)
    at IncomingMessage.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at IncomingMessage.Readable.push (_stream_readable.js:134:10)
    at HTTPParser.parserOnBody (_http_common.js:123:22)
    at Socket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
```

**Comment by pimterry** [comment]
The problem you're having here is simply that there's no `stretch` tag for this base image at all, because the `raspberrypi-debian` image is actually obsolete, and quite out of date (see https://hub.docker.com/r/resin/raspberrypi-debian/).

You can browse all the resin base images at https://hub.docker.com/r/resin/, and there's more detailed documentation on all this over here: https://docs.resin.io/runtime/resin-base-images/

If you replace `raspberrypi-debian:stretch` with [`rpi-raspbian:stretch`](https://hub.docker.com/r/resin/rpi-raspbian/), I think this will give you what you're expecting. Does that work for you?

As an aside, the proper fix for `Dockerfile.template` support is #604 - feel free to subscribe to that one for notifications when this is fully supported!

**Comment by pimterry** [comment]
Although in fact, I've just been reminded that the real problem here is that the `RESIN_MACHINE_NAME` for raspberry pi is `raspberry-pi`, not `raspberrypi` (i.e. you need a dash).

That means you probably wanted [`raspberry-pi-debian:stretch`](https://hub.docker.com/r/resin/raspberry-pi-debian), which will work as well (and should be exactly the same image as `rpi-raspbian:stretch`)

**Comment by lurch** [comment]
(the documentation is getting fixed in https://github.com/resin-io/docs/pull/657 )

**Comment by pimterry** [comment]
@aj-ptw I'm going to close this and assume the above workaround solves your issue, but feel free to ping here if you're still having problems with this.
