### ISSUE TITLE
Failed to install with node 8

### ISSUE THREAD

**Issue by thgreasi** [resin-io/resin-cli#804]
- **resin-cli version:**: 7.0.0
- **Operating system and architecture:** Ubuntu 16.04
- **node -v**: 8.10.0
- **npm -v**: 5.7.1
- **node-gyp -v**: 3.6.2

```
npm WARN deprecated resin-cli-auth@1.2.3: Resin-cli-auth is now built into Resin CLI itself, so this package is not maintained, and should not be used.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
/usr/bin/resin -> /usr/lib/node_modules/resin-cli/bin/resin

> ext2fs@0.1.1 install /usr/lib/node_modules/resin-cli/node_modules/ext2fs
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://github.com/resin-io/node-ext2fs/releases/download/v0.1.1/bindings-v0.1.1-node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for ext2fs@0.1.1 and node@8.10.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/resin-cli/node_modules/ext2fs/build'
gyp ERR! System Linux 4.4.0-116-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/lib/node_modules/resin-cli/node_modules/ext2fs/pregyp/bindings.node" "--module_name=bindings" "--module_path=/usr/lib/node_modules/resin-cli/node_modules/ext2fs/pregyp"
gyp ERR! cwd /usr/lib/node_modules/resin-cli/node_modules/ext2fs
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/resin-cli/node_modules/ext2fs/pregyp/bindings.node --module_name=bindings --module_path=/usr/lib/node_modules/resin-cli/node_modules/ext2fs/pregyp' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/resin-cli/node_modules/ext2fs/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.4.0-116-generic
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/resin-cli/node_modules/ext2fs/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/resin-cli/node_modules/ext2fs
node-pre-gyp ERR! node -v v8.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/resin-cli/node_modules/ext2fs/pregyp/bindings.node --module_name=bindings --module_path=/usr/lib/node_modules/resin-cli/node_modules/ext2fs/pregyp' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: removedrive@1.1.2 (node_modules/resin-cli/node_modules/removedrive):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for removedrive@1.1.2: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: macmount@1.0.0 (node_modules/resin-cli/node_modules/macmount):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for macmount@1.0.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ext2fs@0.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ext2fs@0.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/teo/.npm/_logs/2018-03-10T10_02_04_206Z-debug.log
```

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_9l3t)

**Comment by pimterry** [comment]
@thgreasi this is very odd - the URL it's saying it can't download there (https://github.com/resin-io/node-ext2fs/releases/download/v0.1.1/bindings-v0.1.1-node-v57-linux-x64.tar.gz) works totally fine for me, and that was released in November last year.

Can you reproduce this? Maybe it's an intermittent github issue? We've seen it before too: https://github.com/resin-io/resin-cli/issues/799.

**Comment by thgreasi** [comment]
@pimterry these logs are actually from my machine (`/home/teo/...`) after reproducing what the user faced, by upgrading node to v8. As seen in the linked convo `--unsafe-perm` fixed it both for me and the user.
