### ISSUE TITLE
Multi-stage emulated build fails

### ISSUE THREAD

**Issue by svenschwermer** [resin-io/resin-cli#814]
- **resin-cli version:**
  - 7.0.3
- **Operating system and architecture:**
  - build: linux/amd64
  - target: armv7hf

I'm trying to make use of the multi-stage build feature in recent Docker versions. I am cross-building for armv7hf. This is my Dockerfile:

```
FROM resin/armv7hf-debian AS builder
RUN apt-get update \
    && apt-get install -yq --no-install-recommends build-essential automake
WORKDIR /tmp
ARG SPI_TOOLS_COMMIT=318bcae5249722873bf58b27afdd20473c7047cc
ADD https://github.com/cpb-/spi-tools/archive/${SPI_TOOLS_COMMIT}.tar.gz .
RUN tar xf ${SPI_TOOLS_COMMIT}.tar.gz \
    && cd spi-tools-${SPI_TOOLS_COMMIT} \
    && autoreconf -fim \
    && ./configure -q --prefix=/ \
    && make install

FROM resin/armv7hf-debian
COPY --from=builder /bin/spi-config /bin/spi-pipe /usr/bin/
COPY app /app
CMD /app/start.sh
```

I call the build command like this:
```
$ DEBUG=1 resin build --logs --emulated --application MyApp --projectName MyProject
```
This is the output I get:
```
[Debug]   Parsing input...
[Debug]   Loading project...
[Debug]   Resolving project...
[Debug]   Failed to resolve project: 
[Debug]   AggregateError of:
[Debug]       Error: ENOENT: no such file or directory, open '****/resin-compose.yml'
[Debug]       Error: ENOENT: no such file or directory, open '****/resin-compose.yaml'
[Debug]       Error: ENOENT: no such file or directory, open '****/docker-compose.yml'
[Debug]       Error: ENOENT: no such file or directory, open '****/docker-compose.yaml'
[Info]    Creating default composition with source: ****
[Debug]   Creating project...
[Info]    Building for armv7hf/hummingboard
[Build]   Building services...
[Build]   main          Preparing...
[Info]    Installing qemu for ARM emulation...
[Info]    Emulation is enabled
[Debug]   Prepared tasks; building...
[Build]   main          Step 1/13 : FROM resin/armv7hf-debian AS builder
[Build]   main           ---> af9c05457784
[Build]   main          Step 2/13 : COPY [".resin/qemu-execve","/tmp/qemu-execve"]
[Build]   main           ---> Using cache
[Build]   main           ---> afbcc5c84cb9
[Build]   main          Step 3/13 : RUN ["/tmp/qemu-execve","-execve","/bin/sh","-c","apt-get update && apt-get install -yq --no-install-recommends     build-essential     automake"]
[Build]   main           ---> Using cache
[Build]   main           ---> e0aca16a992a
[Build]   main          Step 4/13 : WORKDIR /tmp
[Build]   main           ---> Using cache
[Build]   main           ---> ea2d9e1e93fb
[Build]   main          Step 5/13 : ARG SPI_TOOLS_COMMIT=318bcae5249722873bf58b27afdd20473c7047cc
[Build]   main           ---> Using cache
[Build]   main           ---> 379505d391fb
[Build]   main          Step 6/13 : ADD ["https://github.com/cpb-/spi-tools/archive/${SPI_TOOLS_COMMIT}.tar.gz","."]
[Build]   main           ---> Using cache
[Build]   main           ---> 444d7158dd2e
[Build]   main          Step 7/13 : RUN ["/tmp/qemu-execve","-execve","/bin/sh","-c","tar xf ${SPI_TOOLS_COMMIT}.tar.gz     && cd spi-tools-${SPI_TOOLS_COMMIT}     && autoreconf -fim     && ./configure -q --prefix=/     && make install"]
[Build]   main           ---> Using cache
[Build]   main           ---> a09ccd12f0f8
[Build]   main          Step 8/13 : FROM resin/armv7hf-debian
[Build]   main           ---> af9c05457784
[Build]   main          Step 9/13 : RUN ["/tmp/qemu-execve","-execve","/bin/sh","-c","apt-get update && apt-get install -yq --no-install-recommends     dbus     curl     && apt-get clean && rm -rf /var/lib/apt/lists/*"]
[Build]   main           ---> Running in bdefd3c8b247
[Build]   Built 1 service in 0:08
[Error]   Build failed
Error: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/tmp/qemu-execve\": stat /tmp/qemu-execve: no such file or directory": unknown
    at Stream.<anonymous> (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/resin-docker-build/build/builder.js:69:33)
    at Stream.stream.write (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/through/index.js:26:11)
    at Stream.ondata (internal/streams/legacy.js:16:26)
    at Stream.emit (events.js:160:13)
    at drain (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/through/index.js:45:5)
    at Parser.parser.onToken (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/JSONStream/index.js:130:18)
    at Parser.proto.write (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/jsonparse/jsonparse.js:135:34)
    at Stream.<anonymous> (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/JSONStream/index.js:21:12)
    at Stream.stream.write (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/through/index.js:26:11)
    at IncomingMessage.ondata (_stream_readable.js:646:20)
    at IncomingMessage.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at IncomingMessage.Readable.push (_stream_readable.js:213:10)
    at HTTPParser.parserOnBody (_http_common.js:130:22)
    at Socket.socketOnData (_http_client.js:439:20)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at Pipe.onread (net.js:602:20)
```

**Comment by dfunckt** [comment]
It seems we're not copying qemu into later stages, so "/tmp/qemu-execve" does not exist. cc @CameronDiver

**Comment by pimterry** [comment]
@svenschwermer this is now fixed in CLI 7.1.6. Thanks for the report! Let us know if you have any other trouble.

**Comment by pimterry** [comment]
@svenschwermer are you sure you're using the latest CLI? You can check with `resin version`. I've just rebuilt the exact Dockerfile above locally with 7.2.2 and it works fine:

```
[Info]    Creating default composition with source: /tmp/tmp.3FrZNHis6F
[Info]    Building for armv7hf/raspberrypi3
[Build]   Building services...
[Build]   main Preparing...
[Info]    Emulation is enabled
[Build]   main Step 1/12 : FROM resin/armv7hf-debian AS builder
[Build]   main  ---> 1fd8cd2c39e7
[Build]   main Step 2/12 : COPY .resin/qemu-execve /tmp/qemu-execve
[Build]   main  ---> Using cache
[Build]   main  ---> e6cb50bea048
[Build]   main Step 3/12 : RUN apt-get update     && apt-get install -yq --no-install-recommends build-essential automake
[Build]   main  ---> Using cache
[Build]   main  ---> ea368e3ba7fc
[Build]   main Step 4/12 : WORKDIR /tmp
[Build]   main  ---> Using cache
[Build]   main  ---> 9d078aee5c99
[Build]   main Step 5/12 : ARG SPI_TOOLS_COMMIT=318bcae5249722873bf58b27afdd20473c7047cc
[Build]   main  ---> Using cache
[Build]   main  ---> 7d2f3cd4fb66
[Build]   main Step 6/12 : ADD https://github.com/cpb-/spi-tools/archive/${SPI_TOOLS_COMMIT}.tar.gz .
[Build]   main  ---> Using cache
[Build]   main  ---> 07fa5e5a1bb4
[Build]   main Step 7/12 : RUN tar xf ${SPI_TOOLS_COMMIT}.tar.gz     && cd spi-tools-${SPI_TOOLS_COMMIT}     && autoreconf -fim     && ./configure -q --prefix=/     && make install
[Build]   main  ---> Using cache
[Build]   main  ---> 24c583d8faaa
[Build]   main Step 8/12 : FROM resin/armv7hf-debian
[Build]   main  ---> 1fd8cd2c39e7
[Build]   main Step 9/12 : COPY .resin/qemu-execve /tmp/qemu-execve
[Build]   main  ---> Using cache
[Build]   main  ---> e6cb50bea048
[Build]   main Step 10/12 : COPY --from=builder /bin/spi-config /bin/spi-pipe /usr/bin/
[Build]   main  ---> Using cache
[Build]   main  ---> 24d0449a0213
[Build]   main Step 11/12 : COPY app /app
[Build]   main  ---> Using cache
[Build]   main  ---> ba4924d7d0ed
[Build]   main Step 12/12 : CMD /app/start.sh
[Build]   main  ---> Using cache
[Build]   main  ---> 49ffdf9c8fc2
[Build]   main Successfully built 49ffdf9c8fc2
[Build]   main Successfully tagged myprojec_main:latest
[Success] Build succeeded!
```

**Comment by svenschwermer** [comment]
Yes, I am sure that I'm using Resin CLI 7.2.2. This is our docker version:
```
Client:
 Version:	18.02.0-ce
 API version:	1.36
 Go version:	go1.10
 Git commit:	019873ef47
 Built:	Fri Mar  9 16:48:23 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.02.0-ce
  API version:	1.36 (minimum version 1.12)
  Go version:	go1.9.3
  Git commit:	fc4de44
  Built:	Wed Feb  7 21:15:09 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```
This is the result:
```
$ DEBUG=1 resin build --logs --emulated --application MYAPP --projectName PROJECT_NAME
[Debug]   Parsing input...
[Debug]   Loading project...
[Debug]   Resolving project...
[Debug]   Failed to resolve project: 
[Debug]   AggregateError of:
[Debug]       Error: ENOENT: no such file or directory, open '/var/lib/****/agent/workspace/_sven.schwermer_multi-stage-7ZKJWPF4LEX4EXPTJCRKJRX24WXOEEIST6MLBO2OKC2A2C5EKATA/resin-compose.yml'
[Debug]       Error: ENOENT: no such file or directory, open '/var/lib/****/agent/workspace/_sven.schwermer_multi-stage-7ZKJWPF4LEX4EXPTJCRKJRX24WXOEEIST6MLBO2OKC2A2C5EKATA/resin-compose.yaml'
[Debug]       Error: ENOENT: no such file or directory, open '/var/lib/****/agent/workspace/_sven.schwermer_multi-stage-7ZKJWPF4LEX4EXPTJCRKJRX24WXOEEIST6MLBO2OKC2A2C5EKATA/docker-compose.yml'
[Debug]       Error: ENOENT: no such file or directory, open '/var/lib/****/agent/workspace/_sven.schwermer_multi-stage-7ZKJWPF4LEX4EXPTJCRKJRX24WXOEEIST6MLBO2OKC2A2C5EKATA/docker-compose.yaml'
[Info]    Creating default composition with source: /var/lib/****/agent/workspace/_sven.schwermer_multi-stage-7ZKJWPF4LEX4EXPTJCRKJRX24WXOEEIST6MLBO2OKC2A2C5EKATA
[Debug]   Creating project...
[Info]    Building for armv7hf/hummingboard
[Build]   Building services...
[Build]   main          Preparing...
[Info]    Installing qemu for ARM emulation...
[Info]    Emulation is enabled
[Debug]   Prepared tasks; building...
[Build]   main          Step 1/12 : FROM resin/armv7hf-debian AS builder
[Build]   main           ---> af9c05457784
[Build]   main          Step 2/12 : COPY [".resin/qemu-execve","/tmp/qemu-execve"]
[Build]   main           ---> Using cache
[Build]   main           ---> 18ff71d55d32
[Build]   main          Step 3/12 : RUN ["/tmp/qemu-execve","-execve","/bin/sh","-c","apt-get update && apt-get install -yq --no-install-recommends     build-essential     automake"]
[Build]   main           ---> Using cache
[Build]   main           ---> 203c2674a655
[Build]   main          Step 4/12 : WORKDIR /tmp
[Build]   main           ---> Using cache
[Build]   main           ---> 4e22224c71f4
[Build]   main          Step 5/12 : ARG SPI_TOOLS_COMMIT=318bcae5249722873bf58b27afdd20473c7047cc
[Build]   main           ---> Using cache
[Build]   main           ---> fb13c7ae9693
[Build]   main          Step 6/12 : ADD ["https://github.com/cpb-/spi-tools/archive/${SPI_TOOLS_COMMIT}.tar.gz","."]
[Build]   main           ---> Using cache
[Build]   main           ---> bd86aaf40c1b
[Build]   main          Step 7/12 : RUN ["/tmp/qemu-execve","-execve","/bin/sh","-c","tar xf ${SPI_TOOLS_COMMIT}.tar.gz     && cd spi-tools-${SPI_TOOLS_COMMIT}     && autoreconf -fim     && ./configure -q --prefix=/     && make install"]
[Build]   main           ---> Using cache
[Build]   main           ---> 6ea2480977a0
[Build]   main          Step 8/12 : FROM resin/armv7hf-debian
[Build]   Built 1 service in 0:04
[Error]   Build failed
Error: COPY failed: stat /var/lib/docker/tmp/docker-builder966551373/--from=builder: no such file or directory
    at Stream.<anonymous> (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/resin-docker-build/build/builder.js:69:33)
    at Stream.stream.write (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/through/index.js:26:11)
    at Stream.ondata (internal/streams/legacy.js:16:26)
    at Stream.emit (events.js:160:13)
    at drain (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/through/index.js:45:5)
    at Parser.parser.onToken (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/JSONStream/index.js:130:18)
    at Parser.proto.write (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/jsonparse/jsonparse.js:135:34)
    at Stream.<anonymous> (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/JSONStream/index.js:21:12)
    at Stream.stream.write (/home/node/.npm-global/lib/node_modules/resin-cli/node_modules/through/index.js:26:11)
    at IncomingMessage.ondata (_stream_readable.js:646:20)
    at IncomingMessage.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at IncomingMessage.Readable.push (_stream_readable.js:213:10)
    at HTTPParser.parserOnBody (_http_common.js:130:22)
    at Socket.socketOnData (_http_client.js:439:20)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at Pipe.onread (net.js:602:20)

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/resin-io/resin-cli/issues/new
  Forums: https://forums.resin.io
```
It looks like an error caused by a too old docker version not supporting multi-stage builds. However, as you can see from the docker version output, docker should be new enough.

**Comment by svenschwermer** [comment]
I found the issue: We still forced an old version of `docker-qemu-transpose` due to issue #747. After removing that constraint, the multi-stage build works as expected.

**Comment by pimterry** [comment]
(Oops, missed the latest comment there)

Great! Let us know if you hit any other problems.
