### ISSUE TITLE
Crash when trying to preload SKX2 app into image

### ISSUE THREAD

**Issue by chenosaurus** [resin-io/resin-cli#859]
- **resin-cli 7.3.0**
- **OS X 10.12.6**

Davids-MacBook-Pro:edge-images dchen$ resin preload resin-xxxx-2.12.5+rev6-v7.1.18.img --app xxxx --commit 4ac552f27ad6fbccb480cfbc8798e2ed0e040d3e
Building Docker preloader image. [========================] 100%

/ Creating preloader container
/ Starting preloader container
| Fetching application 1031618
\ Reading image information
| Resizing partitions and waiting for dockerd to start
Pulling 1 image [===================     ] 81%
| Cleaning up temporary files
{ Error: failed to register layer: Error processing tar file(exit status 1): write /root/workspace/edge1-app/node_modules/process-nextick-args/package.json: no space left on device
    at maybeWrapAsError (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/bluebird/js/release/util.js:61:12)
    at /Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/bluebird/js/release/nodeback.js:38:50
    at onStreamError (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/docker-modem/lib/modem.js:338:5)
    at Stream.onStreamEvent (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/docker-modem/lib/modem.js:326:14)
    at emitOne (events.js:116:13)
    at Stream.emit (events.js:211:7)
    at drain (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/through/index.js:45:5)
    at Parser.parser.onToken (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/JSONStream/index.js:130:18)
    at Parser.proto.write (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/jsonparse/jsonparse.js:135:34)
    at Stream.<anonymous> (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/JSONStream/index.js:21:12)
    at Stream.stream.write (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/through/index.js:26:11)
    at IncomingMessage.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at IncomingMessage.Readable.push (_stream_readable.js:208:10)
    at HTTPParser.parserOnBody (_http_common.js:140:22)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
  cause: Error: failed to register layer: Error processing tar file(exit status 1): write /root/workspace/edge1-app/node_modules/process-nextick-args/package.json: no space left on device
    at maybeWrapAsError (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/bluebird/js/release/util.js:61:12)
    at /Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/bluebird/js/release/nodeback.js:38:50
    at onStreamError (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/docker-modem/lib/modem.js:338:5)
    at Stream.onStreamEvent (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/docker-modem/lib/modem.js:326:14)
    at emitOne (events.js:116:13)
    at Stream.emit (events.js:211:7)
    at drain (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/through/index.js:45:5)
    at Parser.parser.onToken (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/JSONStream/index.js:130:18)
    at Parser.proto.write (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/jsonparse/jsonparse.js:135:34)
    at Stream.<anonymous> (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/JSONStream/index.js:21:12)
    at Stream.stream.write (/Users/dchen/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/through/index.js:26:11)
    at IncomingMessage.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at IncomingMessage.Readable.push (_stream_readable.js:208:10)
    at HTTPParser.parserOnBody (_http_common.js:140:22)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20),
  isOperational: true }

**Comment by pimterry** [comment]
I see there's a 'out of disk space' error in there:

```
{ Error: failed to register layer: Error processing tar file(exit status 1): write /root/workspace/edge1-app/node_modules/process-nextick-args/package.json: no space left on device
```

Any chance your disk is full? Looks like the error is coming from inside Docker, failing as it tries to pull your built image.

**Comment by chenosaurus** [comment]
The disk on my host system has over 200GB available.  It seems like it's failing trying to write to docker container volume.  I see that right before the error happens, it tries to resize the partition:
`| Resizing partitions and waiting for dockerd to start` . 
Could that be not growing the volume by enough?

**Comment by zvin** [comment]
Hello @chenosaurus 
You're probably right on the image not being grown enough.
I need to access your app to investigate why.
Could you please enable support access to the application and send me a link to it on the dashboard: alexis@resin.io .

**Comment by chenosaurus** [comment]
@zvin I think this may be a Mac OS specific issue, we were able to preload the image without any issues on a Ubuntu 16.4 machine.
