### ISSUE TITLE
Preload hangs "Reading image information"

### ISSUE THREAD

**Issue by adamtec** [resin-io/resin-cli#878]
- **resin-cli version:**
resin-cli: 7.4.0
node: 8.9.4
- **Operating system and architecture:**
Centos 7 (x86_64)

I am attempting to preload an OS image with a specific app commit but the command just hangs with 
"Reading image information" that just keeps spinning.

Below are the commands I am basically running:

### Create config.json
`
resin config generate --application $APP_NAME --network ethernet --appUpdatePollInterval 10 --output ./config.json
`
### Download OS for device type
`
resin os download $DEVICE_TYPE -o ./resin.img --version default
`
### Register new device
`
resin device register $APP_NAME --uuid $DEVICE_UUID 
`
### Configure OS image for new device
`
resin os configure ./resin.img --device $DEVICE_UUID --config ./config.json
`
### Preload app version onto image
`
chmod 664 ./resin.img
resin preload ./resin.img --app $APP_ID --commit $APP_COMMIT 
`
**^ hangs...**

### Initialize and flash OS 
`
resin os initialize ./resin.img --type $DEVICE_TYPE --drive /dev/disk2
`

**Comment by zvin** [comment]
Hello @adamtec ,
Can you please rerun `resin preload` with debug enabled and paste the output here ?
```
DEBUG=1 resin preload ./resin.img --app $APP_ID --commit $APP_COMMIT
```

**Comment by adamtec** [comment]
Below is a dump of the debug output. It appears preload.py is trying to use aufs for Docker storage device. Checking Docker it doesn't have aufs enabled but instead overlay/overlay2.
`
[vagrant@localhost Downloads]$ DEBUG=1 resin preload resin.img --app $APP_ID --commit $APP_COMMIT
Building Docker preloader image. [===                     ] 12%
Step 1/7 : FROM docker:17.10.0-ce-dind
Building Docker preloader image. [======                  ] 25%
Step 2/7 : RUN apk update && apk add --no-cache python3 parted btrfs-progs docker util-linux sfdisk file coreutils sgdisk
 ---> Using cache
Building Docker preloader image. [=========               ] 37%
Step 3/7 : COPY ./requirements.txt /tmp/
 ---> Using cache
Building Docker preloader image. [============            ] 50%
Step 4/7 : RUN pip3 install -r /tmp/requirements.txt
 ---> Using cache
Building Docker preloader image. [===============         ] 62%
Step 5/7 : COPY ./src /usr/src/app
 ---> Using cache
Building Docker preloader image. [==================      ] 75%
Step 6/7 : WORKDIR /usr/src/app
 ---> Using cache
Building Docker preloader image. [=====================   ] 87%
Step 7/7 : CMD /usr/src/app/preload.py
 ---> Using cache
 ---> 2fcaf4b82cbb
Successfully built 2fcaf4b82cbb
Building Docker preloader image. [========================] 100%




- Starting preloader container
- Fetching application 1011056
\ Reading image informationWaiting for Docker to start...
- Reading image informationException in thread background thread for pid 110:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/local/bin/dockerd --storage-driver=aufs --data-root=/tmp/tmp667dfl_m/docker --host=tcp://0.0.0.0:36382

  STDOUT:


  STDERR:
time="2018-05-10T23:55:50.365406139Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
time="2018-05-10T23:55:50.376842324Z" level=info msg="libcontainerd: new containerd process, pid: 129"
Error starting daemon: error initializing graphdriver: driver not supported


Traceback (most recent call last):
  File "/usr/src/app/preload.py", line 805, in <module>
    result = method(**data.get("parameters", {}))
  File "/usr/src/app/preload.py", line 765, in get_image_info
    images, supervisor_version = get_images_and_supervisor_version()
  File "/usr/src/app/preload.py", line 653, in get_images_and_supervisor_version
    return _get_images_and_supervisor_version()
  File "/usr/src/app/preload.py", line 628, in _get_images_and_supervisor_version
\ Reading image information    with docker_context_manager(driver, mountpoint):
  File "/usr/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/usr/src/app/preload.py", line 511, in docker_context_manager
    running_dockerd = start_docker_daemon(storage_driver, docker_dir)
  File "/usr/src/app/preload.py", line 480, in start_docker_daemon
    running_dockerd.wait()
  File "/usr/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/local/bin/dockerd --storage-driver=aufs --data-root=/tmp/tmp667dfl_m/docker --host=tcp://0.0.0.0:36382

  STDOUT:


  STDERR:
time="2018-05-10T23:55:50.365406139Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
time="2018-05-10T23:55:50.376842324Z" level=info msg="libcontainerd: new containerd process, pid: 129"
Error starting daemon: error initializing graphdriver: driver not supported
`

**Comment by zvin** [comment]
@adamtec the storage driver used depends on the device type being preloaded. Most use aufs.
If we preloaded this image using overlay2 as storage driver, the device wouldn't be able to run the preloaded container.

I'll keep this issue open so I can add an error message for this case.

**Comment by adamtec** [comment]
Understood. 
Resin OS utilizes balena which uses aufs as its storage driver, correct?
I see flags for preloading using a remote Docker daemon. I guess I can try that route.

What I am looking into is moving towards a production environment. 
This requires flashing lots of SD cards pre-configured for a specific app and assigning a unique device UUID. Only flashing the OS means waiting for the target device to boot up and pull roughly 3-4 GB app images which takes a considerable amount of time on a RPI3 which is why I was looking into preload.

**Comment by jgentes** [comment]
I'm seeing the same problem on Windows 10, although the debug option doesn't show an error..

```
PS C:\Dev\preload> $env:DEBUG=1
PS C:\Dev\preload> resin preload .\resin-.img --app 11111 --splash-image .\resin-logo.p
ng --dockerHost 0.0.0.0 --dockerPort 2375
Building Docker preloader image. [===                     ] 12%
Step 1/7 : FROM docker:17.10.0-ce-dind
Building Docker preloader image. [======                  ] 25%
Step 2/7 : RUN apk update && apk add --no-cache python3 parted btrfs-progs docker util-linux sfdisk file coreutils sgdisk
 ---> Using cache
Building Docker preloader image. [=========               ] 37%
Step 3/7 : COPY ./requirements.txt /tmp/
 ---> Using cache
Building Docker preloader image. [============            ] 50%
Step 4/7 : RUN pip3 install -r /tmp/requirements.txt
 ---> Using cache
Building Docker preloader image. [===============         ] 62%
Step 5/7 : COPY ./src /usr/src/app
 ---> Using cache
Building Docker preloader image. [==================      ] 75%
Step 6/7 : WORKDIR /usr/src/app
 ---> Using cache
Building Docker preloader image. [=====================   ] 87%
Step 7/7 : CMD /usr/src/app/preload.py
 ---> Using cache
 ---> 1beabafcf7ff
Successfully built 1beabafcf7ff
Building Docker preloader image. [========================] 100%



/ Creating preloader container
/ Starting preloader container
- Fetching application 11111
| Reading image information
\ Reading image information <this just continues to spin>
```

**Comment by jgentes** [comment]
Nevermind, seems that I just needed to give it more time.

**Comment by zvin** [comment]
@jgentes can you try without the `.\` before the image name and the splash image name?

**Comment by jgentes** [comment]
Actually, I was wrong, it never completes. I tried without the .\ before the filenames and had the same result. The Pi can download all of the images in about 10 minutes, and that's much slower than my desktop. I've let it spin for at least 20 minutes with no progress.

**Comment by emilm** [comment]
Same issue here on Windows 10.

**Comment by pimterry** [comment]
Thanks for the report @emilm, we'll take a look at that. It'd be useful to have a little more information though:

* Which CLI version are you using?
* Are you using the standalone build, or installing via npm?
* If npm, which node version are you using?

It'd also be helpful to see the debug output from your machine. Can you run your command with a `DEBUG=1` env var set, as in the example below, and paste the output here?

```
DEBUG=1 resin preload ./resin.img --app $APP_ID --commit $APP_COMMIT
```

(@zvin can you take a look into this?)

**Comment by zvin** [comment]
This may have already been in the latest resin-preload versions: 7.0.3 and 6.3.4

**Comment by emilm** [comment]
Sorry for late response but I have been in talks with resin.io team and they found a problem and fixed it. Also they fixed an issue related to older node versions, so I had to upgrade to 10.

After that it worked!

**Comment by tintinp** [comment]
I'm using node v10.13.0, npm v6.4.1, installed with 
`npm install balena-cli -g --production --unsafe-perm` on ubuntu 18.04. I'm seeing this problem and not sure how to solve it.

```Building Docker preloader image. [===                     ] 12%
Step 1/7 : FROM docker:17.10.0-ce-dind
Building Docker preloader image. [======                  ] 25%
Step 2/7 : RUN apk update && apk add --no-cache python3 parted btrfs-progs docker util-linux sfdisk file coreutils sgdisk
 ---> Using cache
Building Docker preloader image. [=========               ] 37%
Step 3/7 : COPY ./requirements.txt /tmp/
 ---> Using cache
Building Docker preloader image. [============            ] 50%
Step 4/7 : RUN pip3 install -r /tmp/requirements.txt
 ---> Using cache
Building Docker preloader image. [===============         ] 62%
Step 5/7 : COPY ./src /usr/src/app
 ---> Using cache
Building Docker preloader image. [==================      ] 75%
Step 6/7 : WORKDIR /usr/src/app
 ---> Using cache
Building Docker preloader image. [=====================   ] 87%
Step 7/7 : CMD ["python3", "/usr/src/app/preload.py"]
 ---> Using cache
 ---> be8635137249
Successfully built be8635137249
Building Docker preloader image. [========================] 100%



\ Creating preloader container
- Starting preloader container
/ Fetching application 1252660
| Reading image informationTraceback (most recent call last):
  File "/usr/src/app/preload.py", line 821, in <module>
    result = method(**data.get("parameters", {}))
  File "/usr/src/app/preload.py", line 781, in get_image_info
    images, supervisor_version = get_images_and_supervisor_version()
  File "/usr/src/app/preload.py", line 663, in get_images_and_supervisor_version
    inner_image_path = get_inner_image_path(mountpoint)
  File "/usr/src/app/preload.py", line 621, in get_inner_image_path
    device_type = get_device_type()
  File "/usr/src/app/preload.py", line 601, in get_device_type
    result = get_json("flash-boot", "device-type.json", image=image)
  File "/usr/src/app/preload.py", line 590, in get_json
    with part.mount_context_manager() as mountpoint:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/src/app/preload.py", line 103, in mount_context_manager
    with losetup_context_manager(image, offset, size) as device:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/src/app/preload.py", line 87, in losetup_context_manager
    device = losetup(*args).stdout.decode("utf8").strip()
  File "/usr/lib/python3.6/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/lib/python3.6/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/usr/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /sbin/losetup -f --show --offset 50331648 --sizelimit 83886080 /img/balena.img

  STDOUT:


  STDERR:
losetup: /img/balena.img: failed to set up loop device: No such file or directory
```
