### ISSUE TITLE
resin local push gives "exec format error"

### ISSUE THREAD

**Issue by eczajk1** [resin-io/resin-cli#880]
- **resin-cli version: 7.4.0**
- **Operating system and architecture: macOS 10.13.4**

I have a Dockerfile (simplified from my actual app):

```Dockerfile
FROM resin/raspberrypi3-node:6-slim

RUN [ "cross-build-start" ]

RUN apt-get update && apt-get install -yq \
    python build-essential bash wget && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN [ "cross-build-end" ]

CMD ["npm", "start"]
```

When I run `sudo resin build -a myapp`, it works:

```
[Info]    Creating default composition with source: /Users/eczajk/Projects/smartswm/thing
[Info]    Building for armv7hf/raspberrypi3
[Build]   Built 1 service in 0:06
[Build]   main Image size: 285.55 MB
[Success] Build succeeded!
```

But if I do `sudo resin local push f12345b.local -s .` (as described [here](https://docs.resin.io/learn/develop/local-mode/#push-over-a-new-project)), I get an error:

```sh
* Building..
- Stopping and removing any previous 'local-app' container
- Uploading build context & starting build...
Step 1/12 : FROM resin/raspberrypi3-node:6-slim
 ---> ac929deb06b0
Step 2/12 : RUN cross-build-start
 ---> Running in 1a8fe3b7f603
standard_init_linux.go:187: exec user process caused "exec format error"
Push failed. Error: The command 'cross-build-start' returned a non-zero code: 1 Error: The command 'cross-build-start' returned a non-zero code: 1
    at Stream.<anonymous> (/Users/redact/.nvm/versions/node/v6.10.3/lib/node_modules/resin-cli/node_modules/resin-sync/build/docker-utils.js:146:23)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:188:7)
    at drain (/Users/redact/.nvm/versions/node/v6.10.3/lib/node_modules/resin-cli/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/Users/redact/.nvm/versions/node/v6.10.3/lib/node_modules/resin-cli/node_modules/through/index.js:45:5)
    at Parser.parser.onToken (/Users/redact/.nvm/versions/node/v6.10.3/lib/node_modules/resin-cli/node_modules/JSONStream/index.js:130:18)
    at Parser.proto.write (/Users/redact/.nvm/versions/node/v6.10.3/lib/node_modules/resin-cli/node_modules/jsonparse/jsonparse.js:135:34)
    at Stream.<anonymous> (/Users/redact/.nvm/versions/node/v6.10.3/lib/node_modules/resin-cli/node_modules/JSONStream/index.js:21:12)
    at Stream.stream.write (/Users/redact/.nvm/versions/node/v6.10.3/lib/node_modules/resin-cli/node_modules/through/index.js:26:11)
    at IncomingMessage.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at IncomingMessage.Readable.push (_stream_readable.js:134:10)
    at HTTPParser.parserOnBody (_http_common.js:123:22)
    at Socket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
```

I think I understand that the `"exec format error"` is related to the content of [this blog post](https://resin.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/). And I can see in the `resin-cli` source that the `resin local` command uses `resin-sync` under the hood, where the `resin build` command uses a different process.

Is there an alternate method of deploying locally for development purposes?

**Comment by pimterry** [comment]
Generally `exec format error` means you're running some code that's intended for a different architecture.

I think the `cross-build` lines here are likely the problem - that's intended for emulating ARM when building on x86, and in a local push you're building ARM on ARM.

If you remove those, does it build with `local push`? That will of course break `resin build` (which needs emulation to build on your x86 machine) but you can pass `--emulated`/`-e` to that command to automatically handle emulation, without having to edit your dockerfile at all. Does that work for you?

**Comment by eczajk1** [comment]
Yes. Yes it does. THANKS!

**Comment by gggitpl** [comment]
> 

--emulated/-e is where it is added, I am a new one. Thank you for any useful reply.
