### ISSUE TITLE
Malformed Token on os configure 

### ISSUE THREAD

**Issue by joshughes** [resin-io/resin-cli#915]
- **resin-cli version: 7.6.2**
- **Operating system and architecture: Ubuntu 16.04**

```
 DEBUG=true resin os configure jetson-v2.13.0+rev1-prod.img --app Fooo
Configuring operating system image
ResinMalformedToken: Malformed token: VALID_API_TOKEN
    at /snapshot/resin-cli/node_modules/resin-token/build/token.js:54:23
    at tryCatcher (/snapshot/resin-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.module.exports.Promise._settlePromiseFromHandler (/snapshot/resin-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise.module.exports.Promise._settlePromise (/snapshot/resin-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise.module.exports.Promise._settlePromiseCtx (/snapshot/resin-cli/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/snapshot/resin-cli/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/snapshot/resin-cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.e.Async.drainQueues (/snapshot/resin-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_cjgb)

**Comment by pimterry** [comment]
Resolved in CLI 7.7.4
