### ISSUE TITLE
Push failed: docker connection refused

### ISSUE THREAD

**Issue by cara** [resin-io/resin-cli#941]
resin-cli version:  7.9.0
macOS 10.13.6

Trying to build the sample application, but some problem with fetching from docker registry appears..
Probably has something to do with my local docker installation. Tried to set a proxy as suggested in the github docker issues but without success...

➜  resinos-sample git:(master) ✗ sudo resin local push 192.168.178.156 --source .
* Building..
- Stopping and removing any previous 'myapp' container
- Uploading build context & starting build...
Step 1/6 : FROM resin/raspberrypi-alpine-node:slim
Push failed. Error: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.2:53: read udp 127.0.0.1:40216->127.0.0.2:53: read: connection refused Error: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.2:53: read udp 127.0.0.1:40216->127.0.0.2:53: read: connection refused
    at Stream.<anonymous> (/Users/severin/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/resin-sync/build/docker-utils.js:146:23)
    at emitOne (events.js:116:13)
    at Stream.emit (events.js:211:7)
    at drain (/Users/severin/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/Users/severin/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/through/index.js:45:5)
    at Parser.parser.onToken (/Users/severin/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/JSONStream/index.js:130:18)
    at Parser.proto.write (/Users/severin/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/jsonparse/jsonparse.js:135:34)
    at Stream.<anonymous> (/Users/severin/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/JSONStream/index.js:21:12)
    at Stream.stream.write (/Users/severin/.nvm/versions/node/v8.9.4/lib/node_modules/resin-cli/node_modules/through/index.js:26:11)
    at IncomingMessage.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at IncomingMessage.Readable.push (_stream_readable.js:208:10)
    at HTTPParser.parserOnBody (_http_common.js:140:22)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)

**Comment by pimterry** [comment]
This looks like a DNS connectivity issue on your device itself, rather than a CLI issue. That typically either means there's something wrong in the network the device is using, or something's gone wrong in the network configuration itself on the device.

This issue tracker is focused on CLI-specific bugs & feature requests, so I'm going to close this for now. Can you post these details on our forums though at https://forums.resin.io, or send it to paid support if you're a customer? We'll be happy to help you out there.
